// Package auth provides API key and JWT authentication for the Mneme cloud server.
//
// Authentication flow:
//  1. Client presents an API key (generated by GenerateAPIKey).
//  2. Server validates the key hash via ValidateAPIKey (constant-time).
//  3. Server issues a short-lived JWT via Manager.GenerateToken.
//  4. Client uses the JWT in subsequent requests (Authorization: Bearer <token>).
//
// The middleware accepts both API keys (X-API-Key header) and JWT tokens
// (Authorization: Bearer header) for gradual migration and flexibility.
package auth

import (
	"context"
	"crypto/rand"
	"crypto/sha256"
	"crypto/subtle"
	"encoding/hex"
	"fmt"
	"sync"
	"time"

	"github.com/golang-jwt/jwt/v5"
)

// ─── API Key ──────────────────────────────────────────────────────────────────

// GenerateAPIKey creates a new API key and its SHA-256 hash.
//
// The raw key is prefixed with "mn_" for easy identification.
// The hash is what you store — never store the raw key.
func GenerateAPIKey() (rawKey string, hashedKey string, err error) {
	bytes := make([]byte, 32)
	if _, err = rand.Read(bytes); err != nil {
		return "", "", fmt.Errorf("generate random bytes: %w", err)
	}

	rawKey = "mn_" + hex.EncodeToString(bytes)
	hash := sha256.Sum256([]byte(rawKey))
	hashedKey = hex.EncodeToString(hash[:])
	return rawKey, hashedKey, nil
}

// ValidateAPIKey checks if a raw API key matches its stored hash.
//
// Uses constant-time comparison to prevent timing attacks.
func ValidateAPIKey(rawKey, hashedKey string) bool {
	if rawKey == "" || hashedKey == "" {
		return false
	}
	hash := sha256.Sum256([]byte(rawKey))
	computed := hex.EncodeToString(hash[:])
	return subtle.ConstantTimeCompare([]byte(computed), []byte(hashedKey)) == 1
}

// ─── JWT Claims ───────────────────────────────────────────────────────────────

// CustomClaims extends registered JWT claims with Mneme-specific fields.
type CustomClaims struct {
	jwt.RegisteredClaims
	Project string `json:"project,omitempty"`
}

// ─── Manager ──────────────────────────────────────────────────────────────────

// KeyEntry represents a stored API key (hash only, raw key is never stored).
type KeyEntry struct {
	ID        string
	Hash      string
	CreatedAt time.Time
}

// Manager handles JWT signing/validation and API key storage.
type Manager struct {
	secret []byte
	keys   map[string]KeyEntry
	mu     sync.RWMutex
}

// NewManager creates a new auth manager with the given JWT signing secret.
func NewManager(secret string) *Manager {
	return &Manager{
		secret: []byte(secret),
		keys:   make(map[string]KeyEntry),
	}
}

// GenerateToken creates a signed JWT for the given subject and project.
func (m *Manager) GenerateToken(subject, project string, ttl time.Duration) (string, error) {
	now := time.Now()
	claims := CustomClaims{
		RegisteredClaims: jwt.RegisteredClaims{
			Subject:   subject,
			Issuer:    "mneme-cloud",
			IssuedAt:  jwt.NewNumericDate(now),
			ExpiresAt: jwt.NewNumericDate(now.Add(ttl)),
		},
		Project: project,
	}

	token := jwt.NewWithClaims(jwt.SigningMethodHS256, claims)
	return token.SignedString(m.secret)
}

// ValidateToken parses and validates a JWT string, returning its claims.
func (m *Manager) ValidateToken(tokenStr string) (*CustomClaims, error) {
	if tokenStr == "" {
		return nil, fmt.Errorf("empty token")
	}

	token, err := jwt.ParseWithClaims(tokenStr, &CustomClaims{}, func(t *jwt.Token) (any, error) {
		if _, ok := t.Method.(*jwt.SigningMethodHMAC); !ok {
			return nil, fmt.Errorf("unexpected signing method: %v", t.Header["alg"])
		}
		return m.secret, nil
	})
	if err != nil {
		return nil, fmt.Errorf("parse token: %w", err)
	}

	claims, ok := token.Claims.(*CustomClaims)
	if !ok || !token.Valid {
		return nil, fmt.Errorf("invalid token claims")
	}

	return claims, nil
}

// AddKey registers an API key hash for authentication.
func (m *Manager) AddKey(id, hash string) {
	m.mu.Lock()
	defer m.mu.Unlock()
	m.keys[id] = KeyEntry{
		ID:        id,
		Hash:      hash,
		CreatedAt: time.Now(),
	}
}

// RemoveKey removes an API key by ID (for rotation/revocation).
func (m *Manager) RemoveKey(id string) {
	m.mu.Lock()
	defer m.mu.Unlock()
	delete(m.keys, id)
}

// ListKeys returns all registered key entries.
func (m *Manager) ListKeys() []KeyEntry {
	m.mu.RLock()
	defer m.mu.RUnlock()
	result := make([]KeyEntry, 0, len(m.keys))
	for _, k := range m.keys {
		result = append(result, k)
	}
	return result
}

// validateAnyKey checks the raw key against all registered key hashes.
func (m *Manager) validateAnyKey(rawKey string) bool {
	m.mu.RLock()
	defer m.mu.RUnlock()
	for _, entry := range m.keys {
		if ValidateAPIKey(rawKey, entry.Hash) {
			return true
		}
	}
	return false
}

// keyIDByRawKey finds the key ID that matches the raw key (for subject claims).
func (m *Manager) keyIDByRawKey(rawKey string) string {
	m.mu.RLock()
	defer m.mu.RUnlock()
	for id, entry := range m.keys {
		if ValidateAPIKey(rawKey, entry.Hash) {
			return id
		}
	}
	return ""
}

// Authenticate validates an API key and returns a short-lived JWT.
//
// This is the main entry point for the "login" flow:
// client sends API key → server returns JWT → client uses JWT for subsequent requests.
func (m *Manager) Authenticate(rawAPIKey string) (string, error) {
	if !m.validateAnyKey(rawAPIKey) {
		return "", fmt.Errorf("invalid API key")
	}

	keyID := m.keyIDByRawKey(rawAPIKey)
	subject := "api-key:" + keyID

	return m.GenerateToken(subject, "", 1*time.Hour)
}

// ─── Context ──────────────────────────────────────────────────────────────────

type contextKey string

const claimsKey contextKey = "mneme_auth_claims"

// FromContext extracts CustomClaims from a request context.
func FromContext(ctx context.Context) (*CustomClaims, bool) {
	claims, ok := ctx.Value(claimsKey).(*CustomClaims)
	return claims, ok
}
